# Generated by Django 4.2.13 on 2024-07-02 09:31

from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.FileField(upload_to='media/documents/', validators=[utils.validators.validate_file_extension])),
                ('kra_certificate', models.FileField(upload_to='media/documents/', validators=[utils.validators.validate_file_extension])),
                ('passport_photo', models.ImageField(upload_to='documents/')),
                ('others', models.FileField(blank=True, upload_to='media/documents/', validators=[utils.validators.validate_file_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, choices=[('geo', 'geo'), ('it', 'it'), ('system_dev', 'system_dev'), ('training', 'training')], max_length=100)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documents', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.documents')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='employees.employee')),
            ],
        ),
    ]
