# Generated by Django 4.2.13 on 2024-06-24 11:47

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', models.FileField(upload_to='media/documents/', validators=[utils.validators.validate_file_extension])),
                ('kra_certificate', models.FileField(upload_to='media/documents/', validators=[utils.validators.validate_file_extension])),
                ('passport_photo', models.ImageField(upload_to='documents/')),
                ('others', models.FileField(blank=True, upload_to='media/documents/', validators=[utils.validators.validate_file_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documents', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.documents')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
