# Generated by Django 4.2.13 on 2024-07-03 09:14

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='kra_certificate',
            field=models.FileField(upload_to='documents/', validators=[utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='national_id',
            field=models.FileField(upload_to='documents/', validators=[utils.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='others',
            field=models.FileField(blank=True, upload_to='documents/', validators=[utils.validators.validate_file_extension]),
        ),
    ]
