# Generated by Django 4.2.13 on 2024-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_equipments_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('geo', 'geo'), ('it', 'it'), ('system_dev', 'system_dev'), ('training', 'training')], max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
