# Generated by Django 4.2.13 on 2024-06-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_department_employee_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='teams',
            new_name='team',
        ),
    ]
