# Generated by Django 4.2.13 on 2024-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_documents_kra_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
